### ISSUE TITLE
app.diagrams.net will stop working for Embed mode

### ISSUE THREAD

**Issue by brainwang** [mgeb/mediawiki-drawio-editor#20]
While clicking edit in wiki page, there is a window prompts:
'app.diagrams.net will stop working for Embed mode. Please use embed.diagrams.net.'

But the original diagram can be shown correctly. but could not be edited.

Can anyone help?

**Comment by MichaelStrasser88** [comment]
Hey, i found a solution that worked for me: 

Locate the file "ext.drawioeditor.js" and change the following lines: 

1) 
from `src: 'https://www.draw.io/?embed=1&proto=json&spin=1&analytics=0&db=0&gapi=0&od=0&picker=0',`
to `src: 'https://embed.diagrams.net/?embed=1&ui=atlas&spin=1&modified=unsavedChanges&proto=json',`

2)
from `this.iframeWindow.postMessage(JSON.stringify(data), 'https://www.draw.io');`
to `this.iframeWindow.postMessage(JSON.stringify(data), 'https://embed.diagrams.net');`

3) 
from `if (e.origin != 'https://www.draw.io')`
to `if (e.origin != 'https://embed.diagrams.net')`

**Comment by mgeb** [comment]
This has been fixed by #23
