### ISSUE TITLE
Extension:DrawioEditor loads endless after save

### ISSUE THREAD

**Issue by Z0mbiel0ne** [mgeb/mediawiki-drawio-editor#29]
I installed the extension according to instructions.

The editor works great. Unfortunately, I cannot save the file. When I click on "Save" the loading animation appears but does not disappear.

Extension:NativeSvgHandler is installed

It looks like this: https://imgur.com/a/i9cjSm8

Errors in Console:

```
Uncaught SyntaxError: Unexpected token o in JSON at position 1
 at JSON.parse (<anonymous>)
 at drawioHandleMessage (<anonymous>:139:396)
```

Hope somebody can help me.
Greetings

**Comment by roadfox** [comment]
i have exactli the same issue, mediawiki 1.35
where you able to solve it?

My error in the console starts with

`jQuery.Deferred exception: error is not defined DrawioEditor.prototype.uploadToWiki/<@https://wiki.cybertech.swiss/load.php?lang=en&modules=ext.collapsiblevector.collapsibleNav%7Cext.drawioeditor%7Cjquery%2Csite%7Cjquery.client%2Ccookie%2Cui%7Cmediawiki.String%2CTitle%2Capi%2Cbase%2Ccldr%2Ccookie%2CjqueryMsg%2Clanguage%2Ctoc%2Cutil%7Cmediawiki.libs.pluralruleparser%7Cmediawiki.page.ready%2Cstartup%7Cmediawiki.page.watch.ajax%7Cskins.vector.legacy.js%7Cuser.defaults&skin=vector&version=1otzv:22:677
fire@https://wiki.cybertech.swiss/load.php?lang=en&modules=ext.collapsiblevector.collapsibleNav%7Cext.drawioeditor%7Cjquery%2Csite%7Cjquery.client%2Ccookie%2Cui%7Cmediawiki.String%2CTitle%2Capi%2Cbase%2Ccldr%2Ccookie%2CjqueryMsg%2Clanguage%2Ctoc%2Cutil%7Cmediawiki.libs.pluralruleparser%7Cmediawiki.page.ready%2Cstartup%7Cmediawiki.page.watch.ajax%7Cskins.vector.legacy.js%7Cuser.defaults&skin=vector&version=1otzv:76:209
fireWith@https://wiki.cybertech.swiss/load.php?lang=en&`

**Comment by Z0mbiel0ne** [comment]
Through a little JS debugging, I found out that this is actually supposed to display an error message.

Something like: "Already Exists" or "File Format Not Supported"

By inserting the following code into LocalSettings.php, the incorrect save works again for me.

```
$ wgEnableUploads = true; # Enable uploads
$ wgFileExtensions [] = 'svg'; # Add SVG to FileExtensions
```

You need [Imagemagick ](https://www.mediawiki.org/wiki/Manual:$wgUseImageMagick)to display the SVG files and thumbnails
