### ISSUE TITLE
The file usage statistics for embadded draw.io images does not work

### ISSUE THREAD

**Issue by samartzidis** [mgeb/mediawiki-drawio-editor#4]
If you go to "Special Pages -> Unused Files" in your wiki, you will see that all the embedded draw.io images show as unused and an admin. Is there any way to fix that?

**Comment by samartzidis** [comment]
Hi, I've created a pull request for that. Thanks.

**Comment by mgeb** [comment]
This has been resolved. See note in #5.

Thank you for the report and the PR!
